from enum import Enum
from typing import Tuple

import numpy as np
import pandas as pd

from .utils import get_norm_channel_name


class GeneratedColumns(str, Enum):
    """Columns generated by the analysis."""

    MEAN_INTENSITY_UNIQUE_VALUE = "MEAN_INTENSITY_UNIQUE_VALUE"
    PHASE = "PHASE"
    MANUAL_SPOT_COLOR = "MANUAL_SPOT_COLOR"


class Phase(str, Enum):
    """Phase of the cell cycle."""

    EARLY_G1 = "EG1"
    G1 = "G1"
    S = "T"  # TODO: why not S?
    G2_M = "G2/M"


class FucciPhases:
    """FUCCI phases normalized intensity.

    TODO: add explanations.
    """

    start_early_G1 = 0
    end_early_G1 = 4
    start_G1 = 5
    end_G1 = 95
    start_S = 96
    end_S = 113
    start_G2_M = 114
    end_G2_M = 255

    @staticmethod
    def get_phase(ch3_value: int, ch4_value: int) -> Tuple[Phase, int, int]:
        """Return the phase of the cell cycle, and its intensity range.

        Parameters
        ----------
        ch3_value : int
            Normalized intensity of channel 3.
        ch4_value : int
            Normalized intensity of channel 4.

        Returns
        -------
        Tuple[Phase, int, int]
            The phase of the cell cycle, and its intensity range (start and end).
        """
        if ch3_value <= 0.1 and ch4_value <= 0.1:
            return Phase.EARLY_G1, FucciPhases.start_early_G1, FucciPhases.end_early_G1
        elif ch3_value <= 0.1 and ch4_value > 0.1:
            return Phase.G1, FucciPhases.start_G1, FucciPhases.end_G1
        elif ch3_value > 0.1 and ch4_value > 0.1:
            return Phase.S, FucciPhases.start_S, FucciPhases.end_S
        else:
            return Phase.G2_M, FucciPhases.start_G2_M, FucciPhases.end_G2_M


def normalize_channel(df: pd.DataFrame, channel: str) -> str:
    """Normalize a single channel, add in place the resulting column to the
    dataframe, and return the new column's name.

    Normalization is performed by subtracting the min and dividing by (max - min).
    Note that the resulting values are rounded to the 2nd decimal.

    Parameters
    ----------
    df : pd.DataFrame
        Dataframe
    channel : str
        Name of the channel to normalize.

    Returns
    -------
    str
        Name of the new column.

    Raises
    ------
    ValueError
        If the dataframe does not contain the mandatory columns.
    """
    # check that the dataframe contains the channek
    if channel not in df.columns:
        raise ValueError(f"Column {channel} not found")

    # normalize channel
    max_ch = df[channel].max()
    min_ch = df[channel].min()
    norm_ch = np.round(
        (df[channel] - min_ch) / (max_ch - min_ch),
        2,  # number of decimals
    )

    # add the new column
    new_column = get_norm_channel_name(channel)
    df[new_column] = norm_ch

    return new_column


def compute_phase_color(df: pd.DataFrame, channel1: str, channel2: str) -> None:
    """Compute the phase color for each spot using the two channels respective
    intensity, and update the dataframe with a unified mean intensity value, phase,
    and RGB color columns.

    TODO: describe the LUT.

    Parameters
    ----------
    df : pd.DataFrame
        Dataframe
    channel1 : str
        Name of the first channel.
    channel2 : str
        Name of the second channel.

    Raises
    ------
    ValueError
        If the dataframe does not contain the normalized channels.
    """
    # sanity check: the normalized channels are present
    for channel in [channel1, channel2]:
        if get_norm_channel_name(channel) not in df.columns:
            raise ValueError(
                f"Column {get_norm_channel_name(channel)} not found, call "
                f"normalize_channel({channel}) on the dataframe."
            )

    # normalized channel names
    channel1_norm = get_norm_channel_name(channel1)
    channel2_norm = get_norm_channel_name(channel2)

    # initialize the lists
    n_rows = len(df)
    mean_intensity_unique = np.zeros(n_rows)
    color_factor = np.zeros(n_rows)
    color_offset = np.zeros(n_rows)
    phase_label = []

    # loop over the rows of the dataframe
    for index, row in df.iterrows():
        ch1_norm = row[channel1_norm]
        ch2_norm = row[channel2_norm]

        # get fucci phase, and its start and end
        phase, start, end = FucciPhases.get_phase(ch1_norm, ch2_norm)
        phase_label.append(phase.value)

        # record factor and offset
        color_factor[index] = end - start
        color_offset[index] = start

        # record unique mean
        if phase == Phase.G1:
            mean_intensity_unique[index] = ch1_norm
        else:
            mean_intensity_unique[index] = ch2_norm

    # compute color intensity, rounded as an int vector
    color_intensity = np.rint(
        mean_intensity_unique * color_factor + color_offset,
    )
    color_str = [f"r={val};g={val};b={val};" for val in color_intensity]

    # update the dataframe
    df[GeneratedColumns.MEAN_INTENSITY_UNIQUE_VALUE] = mean_intensity_unique
    df[GeneratedColumns.PHASE] = phase
    df[GeneratedColumns.MANUAL_SPOT_COLOR] = color_str
